- name: Install dependencies
  apt:
    pkg:
      - python3
      - python3-pip
      - python3-psycopg2

- name: Install patroni
  apt:
    name: patroni

# - name: Install patroni
#   pip:
#     name: patroni
#     extra_args: --user
#   become_user: postgres

- name: Copy patroni config
  template:
    src: patroni.yml.j2
    dest: /var/lib/postgresql/patroni.yml
    owner: postgres
    mode: '0600'

- name: Copy patroni service
  template:
    src: patroni.service.j2
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root

- name: Start patroni service
  systemd:
    name: patroni
    state: started
    daemon_reload: yes
