- hosts: backup
  gather_facts: yes
  become: yes
  roles:
    - postgres
    - pgbackrest

- hosts: etcd
  gather_facts: yes
  become: yes
  roles:
    - role: andrewrothstein.etcd-cluster
      etcd_secure: False
      etcd_iface_public: eth1
      etcd_cluster_name: patroni-cluster

- hosts: pg
  gather_facts: yes
  become: yes
  roles:
    - postgres
    - patroni
    - pgbackrest
